### ISSUE TITLE
GW step 2 - change interface

### ISSUE THREAD

**Issue by slowe** [chrisnorth/mma-resources#12]
- [x] Display the 2 graphs on the same graph by offsetting them vertically and then don't show a y-axis scale to avoid confusion.
- [x] Instead of clicking on a time difference band in the scale bar, the user will be presented with two lines on the graph (one at 10%, one at 90% by default) that they can drag to line up with the data. One will be blue and one will be green. The time difference is then calculated from those two lines.
- [x] Add shading between the two lines
- [x] Rather than the grid squares being automatically selected, the user will type in the grid squares into the input field.
- [x] The range for the time difference heat map should go from white to mid grey rather than white to black to make it easier to see the highlighted areas. 
- [x] The two heat maps will be combined into one with each of the existing arms given a different direction stripes - where they overlap there will be a checkerboard.

**Comment by slowe** [comment]
@chrisnorth Are we definitely combining the heat maps? The background heat maps are different. For the time being I've left it as two heat maps.

**Comment by chrisnorth** [comment]
I think that referred to the fill style of the selected bands for each detector pair, rather than the background heat maps - so the overlap is more obvious (as it has cross-hatch as opposed to stripes in one direction or the other)

________________________________

**Comment by slowe** [comment]
@chrisnorth Great. That means this can be closed.
