### ISSUE TITLE
Need to provide waveform and simulation files for all events

### ISSUE THREAD

**Issue by chrisnorth** [chrisnorth/mma-resources#2]
Need for each event:
- [x] waveform files
- [x] simulation files for mass ratios 0.1-1
- [x] config (M0, D0, t0) 
- [x] event name
- [x] event time & date (ISO format)

**Comment by chrisnorth** [comment]
Update as of #[dae620ad](https://github.com/chrisnorth/mma-resources/commit/dae620ade549f5ca010a9f0e5a2db00aed0e8d6d)

Parameters in [docs/GW/scenario-1.json](https://github.com/chrisnorth/mma-resources/blob/main/docs/gw/scenario-1.json)

- waveform:
   - filename location: `_event_ > GW > files > waveform_csv`
   - file directory: `docs/gw/waveform-fitter/waveforms`
-  simulation files:
    - filename location: `_event_ > GW > simulations_csv` [for q=1.0 only]
    - file directory: `docs/gw/waveform-fitter/resources`
- config:
   - M0 (simulation total mass): `_event_ > GW > simParams > mtot`
   - D0 (simulation distance): `_event_ > GW > simParams > dist`
   - t0 (data merger time): `_event_ > GW > t0_ms` [in milliseconds]
- event name:
   - `_event_ > name`
- event time & date:
   -` _event_ > datetime` (ISO format, including ms)

@slowe will leave open - close if you're happy

**Comment by slowe** [comment]
@chrisnorth I think we will need the files within the `docs/` subdirectory so that they are available for the web.

**Comment by chrisnorth** [comment]
They're all within docs/ but feel free to move them off they're needed in a different location

**Comment by slowe** [comment]
@chrisnorth Perhaps I'm being daft or not seeing them but I can't find e.g. `LVK220617_waveform.csv` or `wf_Mtot5_D50_q1.0.csv`. Are they committed?

**Comment by slowe** [comment]
@chrisnorth Is the `docs/gw/scenario-1.json` file copied over from `data/scenario-1.json` by hand or is it output there from your code? I'm making an update script to run on commit so I could add copying it across part of that script.

**Comment by chrisnorth** [comment]
Sorry - wasn't commited/pushed. Should be there now.

The scenario-1 file is copied manually - could add copying to update process.

**Comment by slowe** [comment]
In the data file there seem to be 3 detector pairs for each event. For the localisation page of the GW workflow we only show 2? How do we/they pick which 2?
