### ISSUE TITLE
Display timing maps

### ISSUE THREAD

**Issue by slowe** [chrisnorth/mma-resources#4]
- [x] Load data on waveforms which will have a `timing_maps` 2D array.
- [x] Custom colour scale
- [x] Adapt the colour scale to the data range if less than 15 (max value) gives 2ms step, otherwise 5ms step size.
- [x] Build grid map
- [x] Make grid squares selectable
- [x] Update input field
- [ ] Scale bar with labels

**Comment by chrisnorth** [comment]
timing map data now in [docs/GW/scenario-1.json](https://github.com/chrisnorth/mma-resources/blob/main/docs/gw/scenario-1.json)

Location: `_event_ > GW > dt_arr > XY` (for detector pair XY)

**Comment by slowe** [comment]
In the data file there seem to be 3 detector pairs for each event. For the localisation page of the GW workflow we only seem to show 2? How do we/they pick which 2?

**Comment by slowe** [comment]
Need to:
* update timing maps from an existing input value (mostly affects page reload)
* show waveforms for each detector pair

**Comment by chrisnorth** [comment]
I will change the scenario file to only include 2 timing maps

**Comment by slowe** [comment]
This has been superceded by issue #12
