### ISSUE TITLE
Switch GH-pages source

### ISSUE THREAD

**Issue by slowe** [chrisnorth/mma-resources#6]
@chrisnorth Can you switch the Github Pages from the `docs/` directory to the `gh-pages` branch? I've refactored how things are done so that the front-end is now built from the `src/` folder into a `dist/` folder which is then put on the `gh-pages` branch by a Github Action. 

The refactoring was to move all the translation code away from the front-end. Each language variant of the site is now built into its own sub-folder which makes it more efficient for the end-user and translation no longer relies on people having javascript enabled/working.

**Comment by chrisnorth** [comment]
Done
